### PR TITLE
Channel based invisibality enabled by default. 

### PR DESCRIPTION
**Pull request by yofukashino**
also the note in settings was objectively wrong

### CODE REVIEW

**Comment by 12944qwerty** [comment]
What the

**Comment by yofukashino** [comment]
> What the

a pr to resolve some issues?

**Comment by 12944qwerty** [comment]
Nah not that. I appreciate the pr. I'm just confused where the AI thing came from lol

**Comment by 12944qwerty** [comment]
This pr changes the behavior completely. It was supposed to be if you disable the `globalInvisibility`, then invisibility will be channel-based and new (unknown) channels will be visible. global invisibility was not meant to be the default (note was correct previously)

The nullish-coalescing operator you used wouldn't do anything anyway since `channels[unknown_id]` would be undefined and not null. You would need to use `||` at which point `(channelWise && channels[channelId]) || globalInvisible` would be done.

**Comment by yofukashino** [comment]
> This pr changes the behavior completely. It was supposed to be if you disable the `globalInvisibility`, then invisibility will be channel-based and new (unknown) channels will be visible. global invisibility was not meant to be the default (note was correct previously)
> 
> The nullish-coalescing operator you used wouldn't do anything anyway since `channels[unknown_id]` would be undefined and not null. You would need to use `||` at which point `(channelWise && channels[channelId]) || globalInvisible` would be done.

I didn't change logic. 
the note was correct previously??? no?

just writing the note doesn't change how it works, when I PRed making the button channel-based it this is what was done.

without this pr if its channel based global invisibility doesn't do anything
let me give you the logic straight

1. check if invisibality is channel based
2. if not then use global invisibality
3. if yes then get invisibality settings for channel
4. if never changed so it would be undefined which is why we use ?? 
5. global invisibality is used as default for channels you havent toogled
6. we have a separate setting to change weather its channel based or global. 

have you even used your own plugin?
the note was wrong, if you wanted the behaviour then the logic was wrong 

this is logic `channelWise ? channels[channelId] ?? globalInvisible : globalInvisible`
channels[channelId] is undefined by default

**Pull request merged**
